version: '2'

services:

  app:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mongo
    # environment:
    #   AUTH_API_PORT: 8081
    #   JWT_SECRET: myfancysecret
    #   USERS_API_ADDRESS: "http://users-api:8083"
